services:
  bot:
    container_name: bot
    command: bash -c "alembic upgrade head && python /bot/app/main.py"
    build: .
    env_file:
      - .env
    ports:
      - "443:443"
    depends_on:
      postgres:
        condition:
          service_healthy
    volumes:
      - .:/bot

  postgres:
    container_name: postgres
    image: postgres:15-bullseye
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data

